### ISSUE TITLE
Unable to connect to portal

### ISSUE THREAD

**Issue by ebolisa** [peterjazenga/ESPconfig#1]
Hi,
Thanks for doing this.
I'm using an ESP32 to test the code but I cannot connect to the portal at 192.168.4.1.
In my project, I copied the upload folder and this's what I get on the console.
What am I missing?
TIA

:12:16.446 -> ..............................WiFi failed to connect
20:13:42.123 -> WiFi AP started
20:13:42.123 -> TRL_Device
20:13:42.123 -> 12345678
20:13:42.123 -> 11
20:13:42.123 -> 1920234864
20:13:42.123 -> Ready.
20:14:20.439 -> E (127037) wifi: age_bss: null bss
20:14:28.231 -> indexPage
20:14:28.231 -> bad file size
20:14:31.994 -> indexPage
20:14:31.994 -> bad file size
20:15:13.218 -> E (179813) wifi: age_bss: null bss
....

**Comment by peterjazenga** [comment]
it depends on spiffs and having the files index.html & 404.html installed on the ESP32
indexPage, bad file size errors indicate the files are not installed
you will get an error first time because config.bin file does not exist until after the first setup is saved
the second error I have never seen, I have no idea what causes it

I found this via google https://github.com/espressif/esp-idf/issues/4634 and it seems to be unrelated to my code

**Comment by ebolisa** [comment]
Surely the html files are not installed. How do I get them onto the ESP? Do I include them in the code itself?

**Comment by peterjazenga** [comment]
https://randomnerdtutorials.com/install-esp8266-filesystem-uploader-arduino-ide/
https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/

**Comment by ebolisa** [comment]
It worked. Thank you.
